from __future__ import annotations

import json
import os
import re
from dataclasses import asdict

from groq import Groq

from simulation_core import SimulationConfig


class AdaptiveDirector:
    def __init__(self):
        self.api_key = os.getenv("GROQ_API_KEY")
        self.model = "llama-3.1-8b-instant"
        self.client = Groq(api_key=self.api_key) if self.api_key else None

    def _chat(self, system: str, user: str, max_tokens: int = 300, temp: float = 0.4) -> str:
        if not self.client:
            return "[offline] Groq API key not configured. Using deterministic fallback intelligence."
        try:
            result = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
                max_tokens=max_tokens,
                temperature=temp,
            )
            return result.choices[0].message.content.strip()
        except Exception as exc:
            return f"[api-error] {exc}"

    def _extract_json(self, text: str):
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if not m:
            return None
        try:
            return json.loads(m.group())
        except Exception:
            return None

    def generate_environment(self, prompt: str) -> dict:
        system = (
            "You generate a self-driving car RL environment. Output only JSON with keys: "
            "environment_name, weather, track_complexity, obstacle_count, car_speed, fog_alpha, description."
        )
        text = self._chat(system, prompt, max_tokens=220, temp=0.6)
        parsed = self._extract_json(text)
        if parsed:
            parsed.setdefault("weather", "clear")
            parsed.setdefault("track_complexity", "moderate")
            parsed.setdefault("obstacle_count", 8)
            parsed.setdefault("car_speed", 2.8)
            parsed.setdefault("fog_alpha", 0.0)
            parsed.setdefault("description", "Adaptive self-driving scenario generated by the director.")
            return parsed
        return {
            "environment_name": "Adaptive Urban Circuit",
            "weather": "clear",
            "track_complexity": "moderate",
            "obstacle_count": 8,
            "car_speed": 2.8,
            "fog_alpha": 0.0,
            "description": "Fallback environment with urban turns, scattered roadblocks, and a single destination.",
        }

    def analyze_failure(self, episode: dict) -> str:
        prompt = json.dumps({
            "collision": episode.get("collision"),
            "score": episode.get("score"),
            "avg_speed": episode.get("avg_speed"),
            "sensors": episode.get("sensor_snapshot"),
            "config": episode.get("config"),
        })
        system = "You are an autonomous driving safety analyst. Explain crash cause, sensor weakness, and a concrete fix in 3 tight sentences."
        text = self._chat(system, prompt, max_tokens=180, temp=0.35)
        if text.startswith("["):
            return "The vehicle likely entered a low-clearance corridor too quickly, lost safe braking margin, and clipped an obstacle. Reduce approach speed when front sensors drop under 0.35 and bias steering toward the side with more free space."
        return text

    def explain_sensor_state(self, sensors, speed: float) -> str:
        system = "Explain the sensor pattern in one short sentence for a self-driving car controller."
        text = self._chat(system, f"speed={speed}, sensors={sensors}", max_tokens=50, temp=0.5)
        if text.startswith("["):
            if sensors[3] < 0.35:
                return "Front clearance is tight, so the agent should brake and steer toward the more open side."
            return "The lane ahead is mostly open, so the agent can keep speed while following the target waypoint."
        return text

    def summarize_training_block(self, history, adaptive: bool = False) -> str:
        if not history:
            return "No training episodes have run yet."
        goals = sum(1 for x in history if x["reached_goal"])
        crashes = sum(1 for x in history if x["collision"])
        avg_score = sum(x["score"] for x in history) / len(history)
        mode = "adaptive co-evolution" if adaptive else "standard training"
        system = "Summarize RL progress in 3 concise professional sentences. Mention stability, success, and next improvement."
        payload = {"mode": mode, "goals": goals, "crashes": crashes, "avg_score": round(avg_score, 2), "episodes": len(history)}
        text = self._chat(system, json.dumps(payload), max_tokens=150, temp=0.4)
        if text.startswith("["):
            return f"In {mode}, the agent completed {goals} successful runs across {len(history)} episodes. It recorded {crashes} collisions with an average score of {avg_score:.2f}, which suggests {'stable learning' if crashes < len(history) * 0.4 else 'the policy still needs stronger obstacle avoidance'}. The next improvement should focus on smoother speed control before dense obstacle zones."
        return text

    def propose_adaptation(self, config: SimulationConfig, latest_episode: dict) -> dict:
        payload = {
            "config": asdict(config),
            "episode": {
                "score": latest_episode["score"],
                "collision": latest_episode["collision"],
                "reached_goal": latest_episode["reached_goal"],
                "path_efficiency": latest_episode["path_efficiency"],
                "avg_speed": latest_episode["avg_speed"],
            },
        }
        system = (
            "You are the adaptive director for a self-driving RL system. Output only JSON with keys: "
            "config (same config keys as input) and analysis. Increase difficulty if the agent is doing well, reduce it if unstable."
        )
        text = self._chat(system, json.dumps(payload), max_tokens=220, temp=0.45)
        parsed = self._extract_json(text)
        if parsed and isinstance(parsed.get("config"), dict):
            return parsed

        new_cfg = asdict(config)
        if latest_episode["reached_goal"] and not latest_episode["collision"]:
            new_cfg["obstacle_count"] = min(18, new_cfg["obstacle_count"] + 1)
            new_cfg["car_speed"] = round(min(4.5, new_cfg["car_speed"] + 0.1), 2)
            if latest_episode["path_efficiency"] > 0.6:
                new_cfg["track_complexity"] = "complex" if config.track_complexity == "moderate" else config.track_complexity
            analysis = "The agent handled the current route cleanly, so the director increased obstacle density and speed to keep learning pressure high."
        elif latest_episode["collision"]:
            new_cfg["obstacle_count"] = max(3, new_cfg["obstacle_count"] - 1)
            new_cfg["car_speed"] = round(max(1.6, new_cfg["car_speed"] - 0.2), 2)
            analysis = "The environment pushed beyond the policy's safe margin, so the director reduced speed and obstacle pressure to rebuild stability."
        else:
            analysis = "The director kept difficulty nearly steady because the policy showed mixed but usable behavior."
        return {"config": new_cfg, "analysis": analysis}
