from __future__ import annotations

import json
import os
import re
from dataclasses import asdict

from groq import Groq

from simulation_core import SimulationConfig, sanitize_weather, normalize_track_complexity


class AdaptiveDirector:
    def __init__(self):
        self.api_key = os.getenv("GROQ_API_KEY")
        self.model = "llama-3.1-8b-instant"
        self.client = Groq(api_key=self.api_key) if self.api_key else None

    def _chat(self, system: str, user: str, max_tokens: int = 300, temp: float = 0.4) -> str:
        if not self.client:
            return "[offline] Groq API key not configured. Using deterministic fallback intelligence."
        try:
            result = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
                max_tokens=max_tokens,
                temperature=temp,
            )
            return result.choices[0].message.content.strip()
        except Exception as exc:
            return f"[api-error] {exc}"

    def _extract_json(self, text: str):
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if not m:
            return None
        try:
            return json.loads(m.group())
        except Exception:
            return None

    # ─── ENVIRONMENT GENERATION (Enhanced) ───────────────────────────────
    def generate_environment(self, prompt: str) -> tuple[dict, str]:
        """Generate environment config AND reasoning from LLM.
        Returns (config_dict, reasoning_text).
        """
        system = (
            "You are an expert autonomous driving simulation designer. "
            "Given a user prompt, design a realistic self-driving RL training environment. "
            "Think carefully about what weather, track complexity, obstacle density, and speed would "
            "create the most educational training scenario. "
            "Output a JSON object with keys: environment_name, weather (clear/rainy/foggy), "
            "track_complexity (simple/moderate/complex), obstacle_count (2-18), car_speed (1.0-4.5), "
            "fog_alpha (0.0-0.45), description. "
            "Before the JSON, write 2-3 sentences explaining your design reasoning."
        )
        text = self._chat(system, prompt, max_tokens=350, temp=0.6)
        parsed = self._extract_json(text)

        # Extract reasoning (everything before the JSON block)
        reasoning = text
        if parsed:
            json_match = re.search(r"\{.*\}", text, re.DOTALL)
            if json_match:
                reasoning = text[:json_match.start()].strip()
            if not reasoning:
                reasoning = "Environment generated based on the provided prompt specifications."

            parsed.setdefault("weather", "clear")
            parsed["weather"] = sanitize_weather(parsed["weather"])
            parsed.setdefault("track_complexity", "moderate")
            parsed["track_complexity"] = normalize_track_complexity(parsed["track_complexity"])
            parsed.setdefault("obstacle_count", 8)
            parsed["obstacle_count"] = max(2, min(18, int(parsed["obstacle_count"])))
            parsed.setdefault("car_speed", 2.8)
            parsed["car_speed"] = round(max(1.0, min(4.5, float(parsed["car_speed"]))), 2)
            parsed.setdefault("fog_alpha", 0.0)
            parsed["fog_alpha"] = round(max(0.0, min(0.45, float(parsed["fog_alpha"]))), 2)
            parsed.setdefault("description", "Adaptive self-driving scenario generated by the director.")
            return parsed, reasoning

        fallback = {
            "environment_name": "Adaptive Urban Circuit",
            "weather": "clear",
            "track_complexity": "moderate",
            "obstacle_count": 8,
            "car_speed": 2.8,
            "fog_alpha": 0.0,
            "description": "Fallback environment with urban turns, scattered roadblocks, and a single destination.",
        }
        return fallback, "Using fallback environment configuration. Connect Groq API for LLM-designed environments."

    # ─── CURRICULUM PLANNING ─────────────────────────────────────────────
    def generate_curriculum_plan(self, config: SimulationConfig, total_episodes: int = 20) -> dict:
        """LLM generates a multi-phase curriculum plan for adaptive training.
        Returns dict with phases, each containing target config adjustments and goals.
        """
        system = (
            "You are an adaptive curriculum designer for autonomous driving RL training. "
            "Given the target environment config, design a 3-phase progressive curriculum plan. "
            "Phase 1 (Foundation): Start EASIER than the target to build basic navigation skills. "
            "Phase 2 (Progression): Gradually increase difficulty toward the target. "
            "Phase 3 (Mastery): Match or slightly exceed the target difficulty. "
            "Output JSON with key 'phases' containing an array of 3 objects, each with: "
            "phase_name, episodes (number of episodes for this phase), "
            "obstacle_count, car_speed, track_complexity, weather, fog_alpha, "
            "goal (text description of what agent should learn), "
            "reward_focus (one of: 'survival', 'progress', 'efficiency', 'speed'). "
            "Also include a top-level 'strategy' key with 1-2 sentence overall strategy description."
        )
        payload = {
            "target_config": asdict(config),
            "total_episodes": total_episodes,
        }
        text = self._chat(system, json.dumps(payload), max_tokens=500, temp=0.5)
        parsed = self._extract_json(text)

        if parsed and "phases" in parsed:
            # Validate and clamp values
            phases = parsed.get("phases", [])
            for phase in phases:
                phase["obstacle_count"] = max(2, min(18, int(phase.get("obstacle_count", 5))))
                phase["car_speed"] = max(1.0, min(4.5, float(phase.get("car_speed", 2.0))))
                phase["track_complexity"] = normalize_track_complexity(phase.get("track_complexity", "simple"))
                phase["weather"] = sanitize_weather(phase.get("weather", "clear"))
                phase["fog_alpha"] = max(0.0, min(0.45, float(phase.get("fog_alpha", 0.0))))
                phase["episodes"] = max(1, min(10, int(phase.get("episodes", 5))))
                phase.setdefault("reward_focus", "progress")
                phase.setdefault("goal", "Improve driving performance.")

            if phases:
                requested_total = max(1, int(total_episodes))
                current_total = sum(int(p.get("episodes", 1)) for p in phases)
                if current_total <= 0:
                    for phase in phases:
                        phase["episodes"] = 1
                    current_total = len(phases)

                scaled = []
                for phase in phases:
                    raw = int(phase.get("episodes", 1))
                    scaled_count = max(1, int(round((raw / current_total) * requested_total)))
                    scaled.append(scaled_count)

                diff = requested_total - sum(scaled)
                index = 0
                while diff != 0 and scaled:
                    if diff > 0:
                        scaled[index % len(scaled)] += 1
                        diff -= 1
                    else:
                        candidate = index % len(scaled)
                        if scaled[candidate] > 1:
                            scaled[candidate] -= 1
                            diff += 1
                    index += 1

                for idx, phase in enumerate(phases):
                    phase["episodes"] = int(scaled[idx])

                parsed["phases"] = phases
            return parsed

        # Deterministic fallback curriculum — gradual progression
        target = asdict(config)
        target_speed = float(target["car_speed"])
        target_obs = int(target["obstacle_count"])
        target_complexity = normalize_track_complexity(target.get("track_complexity", "moderate"))
        # Phase 2 stays on simple track to consolidate learning before jumping complexity
        mid_complexity = "simple" if target_complexity in ("simple", "moderate") else "moderate"
        return {
            "strategy": "Build strong navigation fundamentals on a simple track first, then gradually increase obstacles and speed while keeping the track manageable, finally graduating to the target complexity.",
            "phases": [
                {
                    "phase_name": "Foundation",
                    "episodes": max(4, (total_episodes * 2) // 5),
                    "obstacle_count": max(2, target_obs // 3),
                    "car_speed": round(max(2.0, target_speed * 0.8), 2),
                    "track_complexity": "simple",
                    "weather": "clear",
                    "fog_alpha": 0.0,
                    "goal": "Learn basic track following and obstacle awareness at moderate speed.",
                    "reward_focus": "survival",
                },
                {
                    "phase_name": "Progression",
                    "episodes": max(4, (total_episodes * 2) // 5),
                    "obstacle_count": max(3, (target_obs * 2) // 3),
                    "car_speed": round(max(2.2, target_speed * 0.9), 2),
                    "track_complexity": mid_complexity,
                    "weather": "clear",
                    "fog_alpha": 0.0,
                    "goal": "Build speed confidence and handle increased obstacle density on a familiar track.",
                    "reward_focus": "progress",
                },
                {
                    "phase_name": "Mastery",
                    "episodes": max(3, total_episodes - 2 * ((total_episodes * 2) // 5)),
                    "obstacle_count": target_obs,
                    "car_speed": target_speed,
                    "track_complexity": target_complexity,
                    "weather": sanitize_weather(target.get("weather", "clear")),
                    "fog_alpha": float(target.get("fog_alpha", 0.0)),
                    "goal": "Achieve reliable goal-reaching at full target difficulty.",
                    "reward_focus": "efficiency",
                },
            ],
        }

    # ─── PER-EPISODE LLM EVALUATION & ADAPTATION ────────────────────────
    def evaluate_episode_and_adapt(self, config: SimulationConfig, episode: dict, episode_history: list[dict], phase_info: dict | None = None) -> dict:
        """LLM evaluates the latest episode and outputs adapted config + reward modifiers + analysis.
        Returns dict with keys: config, analysis, reward_modifiers, action_hints.
        """
        recent = episode_history[-3:] if len(episode_history) > 3 else episode_history
        history_summary = [
            {
                "score": round(float(ep.get("score", 0)), 2),
                "collision": ep.get("collision", False),
                "reached_goal": ep.get("reached_goal", False),
                "path_efficiency": round(float(ep.get("path_efficiency", 0)), 3),
                "avg_speed": round(float(ep.get("avg_speed", 0)), 2),
            }
            for ep in recent
        ]

        payload = {
            "current_config": asdict(config),
            "latest_episode": {
                "score": round(float(episode.get("score", 0)), 2),
                "collision": episode.get("collision", False),
                "reached_goal": episode.get("reached_goal", False),
                "path_efficiency": round(float(episode.get("path_efficiency", 0)), 3),
                "avg_speed": round(float(episode.get("avg_speed", 0)), 2),
                "sensors": episode.get("sensor_snapshot", []),
            },
            "recent_history": history_summary,
            "phase": phase_info.get("phase_name", "unknown") if phase_info else "adaptive",
            "phase_goal": phase_info.get("goal", "") if phase_info else "",
        }

        system = (
            "You are an adaptive RL training director. Analyze the latest episode and recent history. "
            "Output JSON with: "
            "1) 'config' - adjusted environment config (environment_name, weather, track_complexity, obstacle_count, car_speed, fog_alpha, description). "
            "2) 'analysis' - 2-sentence explanation of your adaptation decision. "
            "3) 'reward_modifiers' - object with keys: goal_bonus (0-30 extra reward for reaching goal), "
            "progress_bonus (0-5 extra per waypoint), speed_bonus (0-2 for maintaining good speed), "
            "survival_bonus (0-3 per step without collision), smooth_steering_bonus (0-2 for low steering changes). "
            "4) 'action_hints' - object with: prefer_cautious (bool, true if agent should slow down near obstacles), "
            "prefer_aggressive (bool, true if agent is too conservative). "
            "If the agent crashed, make the environment easier. If it reached the goal, make it harder. "
            "Reward modifiers should emphasize whatever the agent currently struggles with."
        )

        text = self._chat(system, json.dumps(payload), max_tokens=450, temp=0.45)
        parsed = self._extract_json(text)

        if parsed and isinstance(parsed.get("config"), dict):
            # Validate config — sanitize all LLM-generated values
            cfg = parsed["config"]
            cfg["obstacle_count"] = max(2, min(18, int(cfg.get("obstacle_count", 5))))
            cfg["car_speed"] = round(max(1.0, min(4.5, float(cfg.get("car_speed", 2.0)))), 2)
            cfg["weather"] = sanitize_weather(cfg.get("weather", "clear"))
            cfg["track_complexity"] = normalize_track_complexity(cfg.get("track_complexity", "moderate"))
            cfg["fog_alpha"] = round(max(0.0, min(0.45, float(cfg.get("fog_alpha", 0.0)))), 2)
            cfg.setdefault("environment_name", config.environment_name)
            cfg.setdefault("description", config.description)

            # Validate reward modifiers
            rm = parsed.get("reward_modifiers", {})
            parsed["reward_modifiers"] = {
                "goal_bonus": max(0, min(30, float(rm.get("goal_bonus", 15)))),
                "progress_bonus": max(0, min(5, float(rm.get("progress_bonus", 2)))),
                "speed_bonus": max(0, min(2, float(rm.get("speed_bonus", 0.5)))),
                "survival_bonus": max(0, min(3, float(rm.get("survival_bonus", 0.8)))),
                "smooth_steering_bonus": max(0, min(2, float(rm.get("smooth_steering_bonus", 0.3)))),
            }

            # Validate action hints
            ah = parsed.get("action_hints", {})
            parsed["action_hints"] = {
                "prefer_cautious": bool(ah.get("prefer_cautious", False)),
                "prefer_aggressive": bool(ah.get("prefer_aggressive", False)),
            }

            parsed.setdefault("analysis", "LLM adapted the environment based on recent performance.")
            return parsed

        # Deterministic fallback
        new_cfg = asdict(config)
        collision = episode.get("collision", False)
        reached_goal = episode.get("reached_goal", False)
        efficiency = float(episode.get("path_efficiency", 0))

        if collision:
            new_cfg["obstacle_count"] = max(2, new_cfg["obstacle_count"] - 1)
            new_cfg["car_speed"] = round(max(1.0, new_cfg["car_speed"] - 0.2), 2)
            analysis = "Agent crashed — reducing environment pressure to rebuild control stability before advancing difficulty."
            reward_mods = {"goal_bonus": 20, "progress_bonus": 3, "speed_bonus": 0.3, "survival_bonus": 1.5, "smooth_steering_bonus": 1.0}
            action_hints = {"prefer_cautious": True, "prefer_aggressive": False}
        elif reached_goal:
            new_cfg["obstacle_count"] = min(18, new_cfg["obstacle_count"] + 1)
            new_cfg["car_speed"] = round(min(4.5, new_cfg["car_speed"] + 0.15), 2)
            analysis = "Agent succeeded — the director is increasing challenge to push the policy's ceiling higher."
            reward_mods = {"goal_bonus": 10, "progress_bonus": 1.5, "speed_bonus": 1.0, "survival_bonus": 0.5, "smooth_steering_bonus": 0.5}
            action_hints = {"prefer_cautious": False, "prefer_aggressive": efficiency < 0.4}
        else:
            analysis = "Mixed performance — holding difficulty steady and emphasizing progress rewards to encourage reaching the destination."
            reward_mods = {"goal_bonus": 15, "progress_bonus": 2.5, "speed_bonus": 0.5, "survival_bonus": 1.0, "smooth_steering_bonus": 0.5}
            action_hints = {"prefer_cautious": efficiency < 0.3, "prefer_aggressive": False}

        return {
            "config": new_cfg,
            "analysis": analysis,
            "reward_modifiers": reward_mods,
            "action_hints": action_hints,
        }

    # ─── REWARD SHAPING ──────────────────────────────────────────────────
    def generate_reward_shaping(self, episode_history: list[dict], current_phase: str = "adaptive") -> dict:
        """LLM analyzes training patterns and outputs dynamic reward modifiers.
        Returns dict with reward modifier values.
        """
        if not episode_history:
            return {
                "goal_bonus": 15,
                "progress_bonus": 2.5,
                "speed_bonus": 0.5,
                "survival_bonus": 1.0,
                "smooth_steering_bonus": 0.5,
            }

        recent = episode_history[-5:] if len(episode_history) > 5 else episode_history
        crash_rate = sum(1 for e in recent if e.get("collision")) / len(recent)
        success_rate = sum(1 for e in recent if e.get("reached_goal")) / len(recent)
        avg_eff = sum(float(e.get("path_efficiency", 0)) for e in recent) / len(recent)

        system = (
            "You are a reward shaping expert for RL self-driving training. "
            "Based on the agent's recent performance pattern, output JSON with optimal reward modifier values: "
            "goal_bonus (0-30), progress_bonus (0-5), speed_bonus (0-2), "
            "survival_bonus (0-3), smooth_steering_bonus (0-2). "
            "If crash rate is high, emphasize survival. If success is low, emphasize progress. "
            "If efficiency is low, emphasize smooth steering."
        )
        payload = {
            "crash_rate": round(crash_rate, 2),
            "success_rate": round(success_rate, 2),
            "avg_efficiency": round(avg_eff, 3),
            "phase": current_phase,
            "episode_count": len(episode_history),
        }
        text = self._chat(system, json.dumps(payload), max_tokens=150, temp=0.35)
        parsed = self._extract_json(text)

        if parsed:
            return {
                "goal_bonus": max(0, min(30, float(parsed.get("goal_bonus", 15)))),
                "progress_bonus": max(0, min(5, float(parsed.get("progress_bonus", 2)))),
                "speed_bonus": max(0, min(2, float(parsed.get("speed_bonus", 0.5)))),
                "survival_bonus": max(0, min(3, float(parsed.get("survival_bonus", 1.0)))),
                "smooth_steering_bonus": max(0, min(2, float(parsed.get("smooth_steering_bonus", 0.5)))),
            }

        # Deterministic fallback based on patterns
        if crash_rate > 0.5:
            return {"goal_bonus": 20, "progress_bonus": 3, "speed_bonus": 0.2, "survival_bonus": 2.5, "smooth_steering_bonus": 1.5}
        elif success_rate > 0.5:
            return {"goal_bonus": 8, "progress_bonus": 1.5, "speed_bonus": 1.5, "survival_bonus": 0.3, "smooth_steering_bonus": 0.5}
        else:
            return {"goal_bonus": 15, "progress_bonus": 2.5, "speed_bonus": 0.5, "survival_bonus": 1.0, "smooth_steering_bonus": 0.5}

    # ─── ACTION GUIDANCE ─────────────────────────────────────────────────
    def generate_action_guidance(self, sensors: list[float], speed: float, goal_angle: float, episode_history: list[dict]) -> dict:
        """LLM suggests action biases based on current sensor state and history.
        Returns dict with speed_bias (-1 to 1) and steer_bias (-1 to 1).
        """
        recent_crashes = sum(1 for e in (episode_history[-3:] if len(episode_history) > 3 else episode_history) if e.get("collision"))

        system = (
            "You are a driving advisor for an RL self-driving car. Given sensor readings (7 values, 0=blocked, 1=clear), "
            "speed, and goal angle, output JSON with: "
            "speed_bias (-1.0 to 1.0, negative=brake, positive=accelerate), "
            "steer_bias (-1.0 to 1.0, negative=left, positive=right), "
            "reasoning (one short sentence). "
            "Be conservative if sensors show obstacles ahead. Be smooth."
        )
        payload = {
            "sensors": [round(s, 2) for s in sensors],
            "speed": round(speed, 2),
            "goal_angle": round(goal_angle, 3),
            "recent_crashes": recent_crashes,
        }
        text = self._chat(system, json.dumps(payload), max_tokens=100, temp=0.3)
        parsed = self._extract_json(text)

        if parsed:
            return {
                "speed_bias": max(-1.0, min(1.0, float(parsed.get("speed_bias", 0.0)))),
                "steer_bias": max(-1.0, min(1.0, float(parsed.get("steer_bias", 0.0)))),
                "reasoning": parsed.get("reasoning", ""),
            }

        # Deterministic fallback
        front = sensors[3] if len(sensors) > 3 else 1.0
        left_open = sum(sensors[:3]) / 3.0 if len(sensors) >= 3 else 0.5
        right_open = sum(sensors[4:]) / 3.0 if len(sensors) >= 7 else 0.5

        if front < 0.3:
            speed_bias = -0.6
            steer_bias = 0.4 if right_open > left_open else -0.4
            reasoning = "Front blocked — braking and steering to open side."
        elif front < 0.55:
            speed_bias = -0.2
            steer_bias = 0.2 if right_open > left_open else -0.2
            reasoning = "Front partially blocked — reducing speed and adjusting course."
        else:
            speed_bias = 0.3
            steer_bias = 0.0
            reasoning = "Path is clear — maintaining speed toward goal."

        return {"speed_bias": speed_bias, "steer_bias": steer_bias, "reasoning": reasoning}

    # ─── EXISTING METHODS (preserved) ────────────────────────────────────
    def analyze_failure(self, episode: dict) -> str:
        prompt = json.dumps({
            "collision": episode.get("collision"),
            "score": episode.get("score"),
            "avg_speed": episode.get("avg_speed"),
            "sensors": episode.get("sensor_snapshot"),
            "config": episode.get("config"),
        })
        system = "You are an autonomous driving safety analyst. Explain crash cause, sensor weakness, and a concrete fix in 3 tight sentences."
        text = self._chat(system, prompt, max_tokens=180, temp=0.35)
        if text.startswith("["):
            return "The vehicle likely entered a low-clearance corridor too quickly, lost safe braking margin, and clipped an obstacle. Reduce approach speed when front sensors drop under 0.35 and bias steering toward the side with more free space."
        return text

    def explain_sensor_state(self, sensors, speed: float) -> str:
        system = "Explain the sensor pattern in one short sentence for a self-driving car controller."
        text = self._chat(system, f"speed={speed}, sensors={sensors}", max_tokens=50, temp=0.5)
        if text.startswith("["):
            if sensors[3] < 0.35:
                return "Front clearance is tight, so the agent should brake and steer toward the more open side."
            return "The lane ahead is mostly open, so the agent can keep speed while following the target waypoint."
        return text

    def summarize_training_block(self, history, adaptive: bool = False) -> str:
        if not history:
            return "No training episodes have run yet."
        goals = sum(1 for x in history if x["reached_goal"])
        crashes = sum(1 for x in history if x["collision"])
        avg_score = sum(x["score"] for x in history) / len(history)
        mode = "adaptive co-evolution" if adaptive else "standard training"
        system = "Summarize RL progress in 3 concise professional sentences. Mention stability, success, and next improvement."
        payload = {"mode": mode, "goals": goals, "crashes": crashes, "avg_score": round(avg_score, 2), "episodes": len(history)}
        text = self._chat(system, json.dumps(payload), max_tokens=150, temp=0.4)
        if text.startswith("["):
            return f"In {mode}, the agent completed {goals} successful runs across {len(history)} episodes. It recorded {crashes} collisions with an average score of {avg_score:.2f}, which suggests {'stable learning' if crashes < len(history) * 0.4 else 'the policy still needs stronger obstacle avoidance'}. The next improvement should focus on smoother speed control before dense obstacle zones."
        return text

    def propose_adaptation(self, config: SimulationConfig, latest_episode: dict) -> dict:
        payload = {
            "config": asdict(config),
            "episode": {
                "score": latest_episode["score"],
                "collision": latest_episode["collision"],
                "reached_goal": latest_episode["reached_goal"],
                "path_efficiency": latest_episode["path_efficiency"],
                "avg_speed": latest_episode["avg_speed"],
            },
        }
        system = (
            "You are the adaptive director for a self-driving RL system. Output only JSON with keys: "
            "config (same config keys as input) and analysis. Increase difficulty if the agent is doing well, reduce it if unstable."
        )
        text = self._chat(system, json.dumps(payload), max_tokens=220, temp=0.45)
        parsed = self._extract_json(text)
        if parsed and isinstance(parsed.get("config"), dict):
            return parsed

        new_cfg = asdict(config)
        if latest_episode["reached_goal"] and not latest_episode["collision"]:
            new_cfg["obstacle_count"] = min(18, new_cfg["obstacle_count"] + 1)
            new_cfg["car_speed"] = round(min(4.5, new_cfg["car_speed"] + 0.1), 2)
            if latest_episode["path_efficiency"] > 0.6:
                new_cfg["track_complexity"] = "complex" if config.track_complexity == "moderate" else config.track_complexity
            analysis = "The agent handled the current route cleanly, so the director increased obstacle density and speed to keep learning pressure high."
        elif latest_episode["collision"]:
            new_cfg["obstacle_count"] = max(3, new_cfg["obstacle_count"] - 1)
            new_cfg["car_speed"] = round(max(1.6, new_cfg["car_speed"] - 0.2), 2)
            analysis = "The environment pushed beyond the policy's safe margin, so the director reduced speed and obstacle pressure to rebuild stability."
        else:
            analysis = "The director kept difficulty nearly steady because the policy showed mixed but usable behavior."
        return {"config": new_cfg, "analysis": analysis}
